# Docker container
services :

  #trinodb 
  trino:
    image: 'trinodb/trino'
    container_name: trino
    volumes:
      - ./etc/catalog:/etc/trino/catalog
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - minio

  #minio server web interface will be accesible on the host at port 9001
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # Port pour l'API S3
      - "9001:9001"   # Port pour le dashboard
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  #postgres metastore
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: iceberg
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: iceberg
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  minio_data:
  pg_data:

