# Docker container
services :
  #minio server web interface will be accesible on the host at port 9001
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # Port pour l'API S3
      - "9001:9001"   # Port pour le dashboard
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/minio_data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data:

